### ISSUE TITLE
[RC] Robustness May Be at Odds with Accuracy [SyxAb30cY7]

### ISSUE THREAD

**Issue by samorr** [reproducibility-challenge/iclr_2019#129] opened 2018-12-23 10:36 UTC
Team Name | Affiliation
------------ | -----------
GrAnDo | University of Wroclaw

* Paper: [Robustness May Be at Odds with Accuracy](https://openreview.net/pdf?id=SyxAb30cY7)
* Forum: [Comments](https://openreview.net/forum?id=SyxAb30cY7&fbclid=IwAR03sHWWIKSVJ-Vdwj914ndWzMc4d-LlGVTif7QYhwP_i4kh9dbjjv2L5k0)

**Comment by koustuvsinha** [comment] 2018-12-23 23:58
Hi @samorr, thank you for your interest in this challenge. If you can re-open this claim by submitting in [our google form](https://docs.google.com/forms/d/e/1FAIpQLSehp6-IcArs4hzWB9gkPsR_abekpZrDXCGf27I5G4vZ5h1kFQ/viewform) it would be helpful for us to track the progress. I am not closing this at the moment, once you submit the form our bot will open the issue and I'll proceed to close this one.

**Comment by samorr** [comment] 2018-12-24 11:33
> Hi @samorr, thank you for your interest in this challenge. If you can re-open this claim by submitting in [our google form](https://docs.google.com/forms/d/e/1FAIpQLSehp6-IcArs4hzWB9gkPsR_abekpZrDXCGf27I5G4vZ5h1kFQ/viewform) it would be helpful for us to track the progress. I am not closing this at the moment, once you submit the form our bot will open the issue and I'll proceed to close this one.

Hi @koustuvsinha, thanks for the information. Our team will submit the form in few days, as soon as we will have our work planned we will be able to fill entire form. Please wait for that with closing this issue.

**Comment by reproducibility-org** [comment] 2019-01-08 21:07
Duplicate of #139

**Closed by reproducibility-org** 2019-01-08 21:07 UTC
