### ISSUE TITLE
[RC] Parameter efficient training of deep convolutional neural networks by dynamic sparse reparameterization [H1xEwsR9FX]

### ISSUE THREAD

**Issue by reproducibility-org** [reproducibility-challenge/iclr_2019#28] opened 2018-10-07 10:42 UTC
| Team Name | Affiliation |
|---|---|
| DeepSparse | Independent; Independent |

 - Paper: [Parameter efficient training of deep convolutional neural networks by dynamic sparse reparameterization](https://openreview.net/pdf?id=H1xEwsR9FX)
 - Forum: [Comments](https://openreview.net/forum?id=H1xEwsR9FX)

**Comment by jimiolaniyan** [comment] 2018-10-08 12:43
@reproducibility-org close

**Comment by jimiolaniyan** [comment] 2018-10-08 12:51
reproducibility-org close

**Comment by jimiolaniyan** [comment] 2018-10-08 13:17
Closing because of incorrect paper id. Reopened with correct id at #31

**Closed** 2018-10-08 23:52 UTC
Labels: in-progress
